blogger/config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

  
  namespace :backend do
    resources :categories, except: :show
    resources :posts
    get '/'              => 'posts#index'
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

end

blogger/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  def self.get_categories(params)
    self.where("name LIKE ?", "%#{params[:q]}%").order(:id).page params[:page]
  end

  def self.save_data(params)
    if params[:id].blank?
      @category = self.new params
      @category.save if @category.valid?
    else
      @category = self.find params[:id]
      @category.update(params)
    end
    @category
  end

end

blogger/app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file

  validates_attachment_content_type :file, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

blogger/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  validates :category, presence: true


  def self.get_posts(params)
    self.joins(:category)
      .where("title LIKE ? OR content LIKE ? OR categories.name LIKE ?", 
        "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
      .order(:id)
      .page params[:page]
  end

  def self.save_post(params, user = User.new)
    # check new record
    if params[:id].blank?
      @post = self.new(params)
      @post.user = user
      @post.save
    else
      # update record
      @post = self.find(params[:id])
      @post.user = user
      @post.update(params)
    end
    @post
  end

  def self.new_stories
    new_post = self.order("id desc").limit(5)
    slide_post = self.order("id desc").limit(5).group("category_id")
    return new_post , slide_post
  end

end

blogger/app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || backend_posts_path
  end

  protected

  def layout_by_resource
    if devise_controller? || user_signed_in?
      "backend-application"
    else
      "application"
    end
  end

end

blogger/app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @categories = Category.get_categories(params)
  end

def new
    @category = Category.new
  end

  def create
    @category = Category.save_data(category_params)
    if @category.valid?
      flash[:success] = "Category was successfully created."
      redirect_to backend_categories_path
    else
      flash[:warning] = "Cannot create post, please try again."
      render :new
    end
  end

  def edit
    get_by_id params[:id]
    unless @category
      flash[:warning] = "Category with id #{params[:id]} not found."
      redirect_to backend_categories_path
      return
    end
    render :new
  end

  def update
    @category = Category.save_data category_params
    if @category.valid?
      flash[:success] = "Category was successfully updated."
      redirect_to backend_categories_path
    else
      flash[:warning] = "Cannot update category, please try again."
      render :edit
    end
  end

  def destroy
    get_by_id params[:id]
    if @category.delete
      flash[:success] = "Category was successfully deleted."
    else
      flash[:warning] = "Cannot delete category, please try again."
    end
    redirect_to backend_categories_path
  end

  private 
    def get_by_id(id)
      begin
        @category = Category.find id
      rescue ActiveRecord::RecordNotFound => e
        @category = nil
      end
    end

  private
    def category_params
      params.require(:category).permit(:name, :id)
    end
end

blogger/app/controllers/backend/posts_controller.rb
class Backend::PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.get_posts(params)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.save_post(post_params, current_user)
    if @post.valid?
      flash[:success] = "Post was successfully created."
      redirect_to backend_posts_path
    else
      flash[:warning] = "Cannot create post, please try again."
      render :new
    end
  end

  def edit
    get_by_id params[:id]
    if @post.nil?
      flash[:warning] = "Post with id #{params[:id]} not found."
      redirect_to backend_posts_path
      return
    end
    render :new
  end

  def update
    @post = Post.save_post(post_params, current_user)
    if @post.valid?
      flash[:success] = "Post was successfully updated."
      redirect_to backend_posts_path
    else
      flash[:warning] = "Cannot update post, please try again."
      render :edit
    end
  end

  def destroy
    get_by_id params[:id]
    if @post.delete
      flash[:success] = "Post was successfully deleted."
    else
      flash[:warning] = "Cannot delete post, please try again."
    end
    redirect_to backend_posts_path
  end

  def show
    get_by_id params[:id]
    if @post.nil?
      flash[:warning] = "Post with id #{params[:id]} not found."
      redirect_to backend_posts_path
    end
  end

  private 
    def get_by_id(id)
      begin
        @post = Post.find(id)
      rescue ActiveRecord::RecordNotFound => e
        @post = nil
      end
    end

  private
    def post_params
      params.require(:post).permit(:category_id, :title, :content, :id)
    end

end

blogger/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

blogger/app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController
  respond_to :json
  def create
    geometry = Paperclip::Geometry.from_file params[:file]
    image = Image.create params.permit(:file, :alt, :hint)
    # byebug
    render json: {
      image: {
        url: image.file.url,
        height: geometry.height.to_i,
        width: geometry.width.to_i
      }
    }, layout: false, content_type: "text/html"
  end
end

blogger/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

blogger/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @new_posts,@slide_posts = Post.new_stories

  end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/backend/categories_helper.rb
module Backend::CategoriesHelper
end

blogger/app/helpers/backend/posts_helper.rb
module Backend::PostsHelper
end

blogger/app/helpers/categories_helper.rb
module CategoriesHelper
end

blogger/app/helpers/tinymce_assets_helper.rb
module TinymceAssetsHelper
end

blogger/app/views/backend/categories/index.html.erb
<div class="container">
  <h3>Categories Index</h3>
  <hr>
  <div class="row">
    <div class="panel panel-primary filterable">
      <div class="panel-heading">
        <h3 class="panel-title">Categories</h3>
        <form method="GET" > 
          <button type="submit" class="btn btn-warning btn-xs pull-right"><span class="glyphicon glyphicon-filter"></span> Search</button>
          <div class="pull-right">
            <input type="text"  name="q" placeholder="Search" value="<%= params['q']%>" class="form-control">
          </div>
        </form>

        <div class="pull-right">
          <%= link_to raw('<span class="glyphicon glyphicon-filter"></span> Add ') , new_backend_category_path ,:class => "btn btn-success btn-xs" %>
          <button class="btn btn-info btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
        </div>
      </div>
      <table class="table">
        <thead>
          <tr class="filters">
            <th><input type="text" class="form-control" placeholder="#" disabled></th>
            <th><input type="text" class="form-control" placeholder="name" disabled></th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each_with_index do |category, index|%>
            <tr>
              <td><%= index + 1%></td>
              <td><%= category.name%></td>
              
              <td>
                <%= link_to 'Edit', edit_backend_category_path(category) ,:class => "btn btn-warning" %> 
                <%= link_to 'Delete', backend_category_path(category),  data: { confirm: 'Are you sure?' }, method: :delete ,:class => "btn btn-danger" %>
              </td>
            </tr>
          <% end unless @categories.blank?%>
        </tbody>
      </table>
    </div>
    <%= paginate @categories %>
  </div>
</div>
<%= stylesheet_link_tag 'backend/posts', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'backend/posts', 'data-turbolinks-track' => true %>

blogger/app/views/backend/categories/new.html.erb
<div class="container">
  <h3>Category New</h3>
  <hr>
  <div class="row">
    <div class="panel panel-primary filterable">
      <div class="panel-heading">
        <h3 class="panel-title">New Category</h3>
        <div class="pull-right">
            
        </div>
      </div>
     <% url = action_name == 'edit' ? backend_category_path(@category) : backend_categories_path(@category)%>
      <%= semantic_form_for @category, :url => url, html: { id: :posts_form } do |f| %>
      <div class="form-group">
      <%= f.inputs do %>
          <%= f.input :name, input_html: { class: 'form-control', id: "nameCategory"} %>
          <%= f.input :id, as: :hidden%>
      <%end%>
      <%= f.actions do %>
        <%= f.action :submit, :as => :button, button_html: { class: 'btn btn-primary' }%>
        <%= f.action :cancel, :as => :link %>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

<style type="text/css">
  .form-group > fieldset > ol > li {
    list-style: none outside none;
  }
  .label {
    color: black;
  }
</style>

blogger/app/views/backend/posts/_list.html.erb
<% posts.each_with_index do |post, index|%>
  <tr>
      <td><%= index + 1%></td>
      <td><%= post.title%></td>
      <td><%= truncate(strip_tags(post.content), length: 255, omission: '... (continued)') %></td>
      <td><%= post.try(:category).try(:name)%></td>
      <td><%=post.tag%></td>
      <td>
        <%= link_to 'Edit', edit_backend_post_path(post) ,:class => "btn btn-warning" %> 
        <%= link_to 'Show', backend_post_path(post) ,:class => "btn btn-info" %> 
        <%= link_to 'Delete', backend_post_path(post),  data: { confirm: 'Are you sure?' }, method: :delete ,:class => "btn btn-danger" %>
      </td>
  </tr>
<% end unless posts.blank?%>

blogger/app/views/backend/posts/index.html.erb
<div class="container">
  <h3>Post Index</h3>
  <hr>
  <div class="row">
    <div class="panel panel-primary filterable">
      <div class="panel-heading">
        <h3 class="panel-title">Posts</h3>
        <form method="GET" >    
          <button type="submit" class="btn btn-warning btn-xs pull-right"><span class="glyphicon glyphicon-filter"></span> Search</button>
          <div class="pull-right">
            <input type="text"  name="q" placeholder="filters" value="<%= params['q']%>" class="form-control">
          </div>
        </form>

        <div class="pull-right">
          <!-- <button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-filter"></span> Add </button> -->
          <%= link_to raw('<span class="glyphicon glyphicon-filter"></span> Add ') , new_backend_post_path ,:class => "btn btn-success btn-xs" %>
          <button class="btn btn-info btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          
        </div>
      </div>
      <table class="table">
        <thead>
          <tr class="filters">
            <th><input type="text" class="form-control" placeholder="#" disabled></th>
            <th><input type="text" class="form-control" placeholder="title" disabled></th>
            <th><input type="text" class="form-control" placeholder="content" disabled></th>
            <th><input type="text" class="form-control" placeholder="category" disabled></th>
            <th><input type="text" class="form-control" placeholder="tag" disabled></th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <%=render :partial=> 'backend/posts/list' ,:locals =>{:posts => @posts} %>
        </tbody>
      </table>
    </div>
    <%= paginate @posts %>
  </div>
</div>
<%= stylesheet_link_tag 'backend/posts', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'backend/posts', 'data-turbolinks-track' => true %>

blogger/app/views/backend/posts/new.html.erb
<div class="container">
  <h3>Post New</h3>
  <hr>
  <div class="row">
    <div class="panel panel-primary filterable">
      <div class="panel-heading">
        <h3 class="panel-title">New Posts</h3>
        <div class="pull-right">
            
        </div>
      </div>
     <% url = action_name == 'edit' ? backend_post_path(@post) : backend_posts_path(@post)%>
      <%= semantic_form_for @post, :url => url, html: { id: :posts_form } do |f| %>
      <div class="form-group">
      <%= f.inputs do %>
          <%= f.input :category, input_html: { class: 'form-control' } %>
          <%= f.input :title, input_html: { class: 'form-control', id: "titlePost"} %>
          <%= f.input :content, input_html: { class: 'form-control tinymce', id: 'contentPost' } %>
          <%= f.input :tag, input_html: { class: 'form-control', id: "tagPost"} %>
          <%= f.input :id, as: :hidden%>
      <%end%>
      <%= f.actions do %>
        <%= f.action :submit, :as => :button, button_html: { class: 'btn btn-primary' }%>
        <%= f.action :cancel, :as => :link %>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

<style type="text/css">
  .form-group > fieldset > ol > li {
    list-style: none outside none;
  }
  .label {
    color: black;
  }
</style>

<%= tinymce %>

blogger/app/views/backend/posts/show.html.erb
<div class="container">
  <h3>Show Post</h3>
  <hr>
  <div class="row">
    <div class="panel panel-primary filterable">
      <div class="panel-heading">
        <h3 class="panel-title">Show Posts</h3>
        <div class="pull-right">
            
        </div>
      </div>
      <h1 class="page-header">
        <%=@post.title%>

        <p class="lead">
          By <a href="#"><%= @post.try(:user).try(:email)%></a>
        </p>
        <!-- Date/Time -->
        <p class="lead-sub">
          <i class="fa fa-calendar"></i> 
          Posted on <%= @post.created_at.strftime("%B %d at %I:%M %p")%>
        </p>
      </h1>

      <p><%=raw @post.content%></p>
  </div>
</div>

blogger/app/views/layouts/_frontend_nav.html.erb
<div class="header">
  <div class="header-top">
    <div class="header-in">
      <div class="logo">
        <a href="index.html">
          <%= image_tag("logo.png")%>
        </a>
      </div>
      <div class="search">
        <form>
          <input type="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}" >
          <input type="submit" value="SEARCH">
        </form>
      </div>
      <div class="clearfix"> </div>
    </div>
    <div class="header-top-on">
      <ul class="social-in">
        <li><a href="#"><i> </i></a></li>
        <li><a href="#"><i class="facebook"> </i></a></li>
        <li><a href="#"><i class="tin"> </i></a></li>
          
      </ul>
    </div>
    <div class="clearfix"> </div>
  </div>
  <!---->
  <div class="header-bottom">
    <div class="navigation">
      <div>
        <label class="mobile_menu" for="mobile_menu">
        <span>Menu</span>
        </label>
        <input id="mobile_menu" type="checkbox">
        <ul class="nav">
          <li><a class="color1" href="/">Home</a></li>
          <li><a href="#" class="color2">About us</a></li>
          
          <li><a href="#" class="color5">Archives</a></li>
          <li><a href="#" class="color6">Contact us</a></li>
          <% if user_signed_in? %>
            <!-- <li><%#= link_to 'Edit account', edit_user_registration_path %></li> -->
            <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
          <%else%>
            <li><%= link_to 'Sign in', new_user_session_path,:class=> "color3" %></li>
          <%end -%>
          <div class="clearfix"></div>
        </ul>
      </div>
    </div>
  </div>
</div>

blogger/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

blogger/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Post', backend_posts_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

blogger/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Categories', backend_categories_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% end %>

blogger/app/views/layouts/application-old.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blogger" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blogger" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blogger" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blogger" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!--header-->
    <div class="back">
      <%= image_tag("back.png")%>
    </div>
    <div class="container">
      <div class="main-top">
        <div class="main">
          <%= render 'layouts/frontend_nav' %>
          <%= yield %>
        </div>
        <i class="line"> </i>
        <i class="line-in"> </i>
        <i class="line-in line-in1"> </i>
        <i class="line-in line-in2"> </i>
      </div>
      <p class="footer-class">Ruby Programming Challenge 2015 </p>
      <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
    </div>
  </body>
</html>

blogger/app/views/layouts/backend-application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blogger" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blogger" %>">
    <%= stylesheet_link_tag 'backend-application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'backend-application', 'data-turbolinks-track' => true %>
    <%= tinymce_assets %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      
      <%= render 'layouts/navigation' if user_signed_in? %>

    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

blogger/app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

blogger/app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

blogger/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

blogger/app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

blogger/app/views/visitors/_main_stories.html.erb
<div class="number">
  <div class="feb">
    <b><%=post.created_at.to_date.day%></b>
    <label><%=post.created_at.to_date.strftime("%b")%></label>
  </div>
  <!-- </div> -->
  <h3><a href="#"><%= post.title %></a></h3>
  <%= raw post.content %>
  <!---->		
  <div class="movie">
    <ul class="comment">
      <li><span>Category : <a href="#"> <%=post.category.name%></a> </span></li>
      <li><a href="#"><i> </i>0 Comments  </a></li>
    </ul>
    <a class="more" href="#">Read More </a>
    <div class="clearfix"> </div>
  </div>
</div>

blogger/app/views/visitors/_new_stories.html.erb
<div class="gallery">
  <h1>New Stories</h1>
  <div id="owl-demo" class="owl-carousel ">
    <% posts.each_with_index do |post,index| %>
      <div class="item g<%=index%>" style="">
        <a href="#">
        <% html = Nokogiri::HTML.fragment(post.content) %>
        <% image_slide = html.css('img').collect(&:to_s) %>
        <%= raw image_slide[0]%>
        </a>
        <div class="caption">
          <h3 class="cinema"><a href="#"><%=post.category.name%> </a></h3>
          <p><%= truncate(strip_tags(post.content), length: 100, omission: '... read more') %></p>
        </div>
      </div>

    <% end -%>
  </div>
</div>

blogger/app/views/visitors/_tag_cloud.html.erb
<!---->
<div class="grid-top-in">
  <h4>Tag cloud</h4>
  <p>
    <a class="jol" href="#">Angelina Jolie</a>
    <a class="lop" href="#"> Cssauthor</a> 
    <a class="bun" href="#">Aristokrasi Beyonce Blake</a>
    <a class="live" href="#">Lively Brad Pitt Cameron</a> 
    <a class="dan" href="#">Diaz Daniel</a> 
    <a class="jol" href="#"> Radcliffe David</a> 
    <a class="live" href="#">Beckham Demi Moore Emma </a>
    <a class="eva" href="#">Watson Eva</a>
    <a class="live" href="#">Longoria Gisele </a>
    <a class="bun" href="#">Bundchen Gwyneth Paltrow</a>

    <!---
      <a href="#" class="live">Cruz Reese Witherspoon Reklam</a> 
      <a href="#" class="lop"> Rihanna</a> 
      <a href="#" class="live">Robert Pattin </a>
      <a href="#" class="bun">Son Sarah</a> 
      <a href="#" class="live">Jessica </a>
      <a href="#" class="jol">Parker Scar </a> 
      -->
  </p>
</div>

blogger/app/views/visitors/index.html.erb
<%= render :partial => "visitors/new_stories" ,:locals => {:posts => @slide_posts } %>

<div class="content">
  <div class="col-md-8 content-top">
    <% @new_posts.each do |post| %>
     <%= render :partial => "visitors/main_stories" , :locals => {:post => post} %>
    <%end%>
    <!---->
    <div class="older-top">
      <a class="older" href="#"><i> </i>older posts</a>
      <a class="older top-old" href="#"><i> </i>newer posts</a>
      <div class="clearfix"> </div>
    </div>
    <!---->
  </div>
  <!---->
  <div class="col-md-4 content-bottom">
    <div class="story">
      <h4 class="stories"><span>Top Stories</span></h4>
    </div>
    
  <%#= render :partial => "visitors/top_stories" %>

  <%#= render :partial => "visitors/tag_cloud" %>
    
    <!---->
  </div>
  <div class="clearfix"></div>
</div>